-- LIBRARIES
INSERT INTO LIBRARY VALUES (1,'Test Library 1','Kevin Bardool'		,'2017-01-01','testfile1.libr','description of file 1');
INSERT INTO LIBRARY VALUES (2,'Test Library 2','Valadimir Putin'	,CURRENT_DATE,'testfile2.libr','description of file 2');
INSERT INTO LIBRARY VALUES (3,'Test Library 3','Ban Ki Moon    '	,CURRENT_DATE,'testfile3.libr','description of file 3');
INSERT INTO LIBRARY VALUES (4,'Test Library 4','Barack Obama '		,CURRENT_DATE,'testfile4.libr','description of file 4');
INSERT INTO LIBRARY VALUES (5,'Test Library 5','Francois Hollande'	,CURRENT_DATE,'testfile5.libr','description of file 5');
INSERT INTO LIBRARY VALUES (6,'Test Library 6','David Cameron'		,CURRENT_DATE,'testfile6.libr','description of file 6');
INSERT INTO LIBRARY VALUES (7,'Test Library 7','Justin Trudeau'   	,CURRENT_DATE,'testfile7.libr','description of file 7');
INSERT INTO LIBRARY VALUES (8,'Test Library 8','Justin Trudeau'   	,CURRENT_DATE,'testfile8.libr','description of file 8');
INSERT INTO LIBRARY VALUES (9,'Test Library 9','Justin Trudeau'   	,CURRENT_DATE,'testfile9.libr','description of file  9');
INSERT INTO LIBRARY VALUES (10,'Test Library 10','Justin Trudeau'   ,CURRENT_DATE,'testfile10.libr','description of file 10');
INSERT INTO LIBRARY VALUES (11,'Test Library 11','Justin Trudeau'   ,CURRENT_DATE,'testfile11.libr','description of file 11');
INSERT INTO LIBRARY VALUES (12,'Test Library 12','Valadimir Putin'	,CURRENT_DATE,'testfile12.libr','description of file 12');
INSERT INTO LIBRARY VALUES (13,'Test Library 13','Ban Ki Moon    '	,CURRENT_DATE,'testfile13.libr','description of file 13');
INSERT INTO LIBRARY VALUES (14,'Test Library 14','Barack Obama '	,CURRENT_DATE,'testfile14.libr','description of file 14');
INSERT INTO LIBRARY VALUES (15,'Test Library 15','Francois Hollande',CURRENT_DATE,'testfile15.libr','description of file 15');
INSERT INTO LIBRARY VALUES (16,'Test Library 16','David Cameron'	,CURRENT_DATE,'testfile16.libr','description of file 16');
INSERT INTO LIBRARY VALUES (17,'Test Library 17','Justin Trudeau'   ,CURRENT_DATE,'testfile17.libr','description of file 17');
INSERT INTO LIBRARY VALUES (18,'Test Library 18','Justin Trudeau'   ,CURRENT_DATE,'testfile18.libr','description of file 18');
INSERT INTO LIBRARY VALUES (19,'Test Library 19','Justin Trudeau'   ,CURRENT_DATE,'testfile19.libr','description of file 19');
INSERT INTO LIBRARY VALUES (20,'Test Library 20','Justin Trudeau'   ,CURRENT_DATE,'testfile20.libr','description of file 20');
--USERS
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('kbardool@gmail.com','12345',TRUE); 
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('kbardool@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('KBARDOOL@AOL.COM' ,'12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('test2@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('test3@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('test4@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('test5@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('test6@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('test7@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('test8@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('roleuser@outlook.com','12345',TRUE);
INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('superuser@outlook.com','12345',TRUE);

--AUTHORITIES
INSERT INTO AUTHORITIES (USERNAME,AUTHORITY) VALUES ('kbardool@gmail.com','ROLE_ADMIN');
INSERT INTO AUTHORITIES (USERNAME,AUTHORITY) VALUES ('roleuser@outlook.com','ROLE_USER');
INSERT INTO AUTHORITIES (USERNAME,AUTHORITY) VALUES ('superuser@outlook.com','ROLE_SUPER_USER');

--LOG
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 1');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 2');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 3');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 4');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 5');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 6');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 7');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 8');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 9');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 10');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 11');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 12');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 13');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 14');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 15');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 16');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 17');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 18');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 19');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 20');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 21');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 22');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 23');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 24');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 25');
INSERT INTO LOG(LOGSTRING) VALUES('TEST LOG 26');

--TEST
INSERT INTO TEST(TESTCOLUMN) VALUES('TEST COLUMN 1');
INSERT INTO TEST(TESTCOLUMN) VALUES('TEST COLUMN 2');
INSERT INTO TEST(TESTCOLUMN) VALUES('TEST COLUMN 3');
INSERT INTO TEST(TESTCOLUMN) VALUES('TEST COLUMN 4');



